# -*- coding: utf-8 -*-
"""31/01/2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WF7eo1l-OnMVo71TuF2rzXx4t-Oq8E88
"""

from google.colab import files
 uploaded = files.upload()

import pandas as pd
 df = pd.read_csv('NewspaperData.csv')
 df.head()

import seaborn as sns
sns.distplot(df['daily'])

#fitting a linear regression model
 import statsmodels.formula.api as smf
 model = smf.ols('sunday~daily',data=df).fit()
 sns.regplot(x='daily',y='sunday',data=df)